#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.
count=1
while [ $count -le 100 ]
do
	if [ $((count % 5)) -eq 0 -a $((count % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((count % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((count % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$count"
	fi
	count=$((count+1))
done
